name: Upload Release
description: Uploads a built release file

inputs:
  artifact_name:
    description: Artifact name
    required: true
  package_name:
    description: Package name
    required: true
  aws_key_id:
    description: AWS access key ID
    required: true
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_end_point:
    description: AWS end point
    required: true
  github_token:
    description: GitHub Token
    required: false
  upload_aws:
    description: Upload artifact to AWS
    required: true
    default: true

runs:
  using: composite
  steps:
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_name }}
        path: ${{ runner.temp }}/build/${{ inputs.artifact_name }}

    # - name: Upload build to S3 Bucket
    #   if: github.event_name == 'push'
    #   working-directory: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}
    #   run: |
    #     aws configure set aws_access_key_id ${{ inputs.aws_key_id }}
    #     aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }}
    #     aws s3 cp ${{ inputs.artifact_name }} s3://qgroundcontrol/builds/${{ github.ref_name }}/${{ inputs.artifact_name }} --region us-west-2 --acl public-read
    #   shell: bash

    # - name: Upload stable build to S3 Bucket
    #   if: ${{ inputs.upload_aws && github.event_name == 'push' && !github.event.pull_request.head.repo.fork && inputs.aws_key_id != '' && inputs.aws_secret_access_key != '' }}
    #   working-directory: ${{ runner.temp }}/build/${{ inputs.source }}
    #   run: aws s3 cp ${{ inputs.artifact_name }} s3://qgroundcontrol/builds/${{ github.ref_name }}/${{ inputs.artifact_name }} --acl public-read
    #   shell: bash

    # - name: Upload tagged stable build to S3 latest Bucket
    #   if: ${{ inputs.upload_aws && github.event_name == 'push' && github.ref_type == 'tag' && !github.event.pull_request.head.repo.fork && inputs.aws_key_id != '' && inputs.aws_secret_access_key != '' }}
    #   working-directory: ${{ runner.temp }}/build/${{ inputs.source }}
    #   run: aws s3 cp ${{ inputs.artifact_name }} s3://qgroundcontrol/latest/${{ inputs.artifact_name }} --acl public-read
    #   shell: bash

# Commented out since it is 100% fail in CI
#    - name: Create Continuous Release
#      if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' && inputs.github_token != '' }}
#      uses: Wandalen/wretry.action@master
#      with:
#        action: softprops/action-gh-release@v2
#        with: |
#          tag_name: latest
#          target_commitish: master
#          files: ${{ runner.temp }}/build/${{ inputs.source }}/${{ inputs.artifact_name }}
#          name: "Continuous Release"
#          body: "This release is continuously updated with every commit to master."
#          draft: false
#          prerelease: true
#          token: ${{ inputs.github_token }}
