name: Upload Release
description: Uploads a built release file
inputs:
  artifact_name:
    description: artifact name
    required: true
  minio_access_key:
    description: minio access key
    required: true
  minio_secret_key:
    description: minio secret key
    required: true
  minio_endpoint:
    description: minio endpoint
    required: true
  source:
    description: source location
    required: false
    default: package
runs:
  using: "composite"
  steps:
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}/${{ inputs.artifact_name }}

    - name: Upload build to Minio Bucket
      if: github.event_name == 'push'
      working-directory: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}
      run: |
        export MINIO_ACCESS_KEY=${{ inputs.minio_access_key }}
        export MINIO_SECRET_KEY=${{ inputs.minio_secret_key }}
        export MINIO_ENDPOINT=${{ inputs.minio_endpoint }}
        
        mc config host add minio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
        mc cp ${{ inputs.artifact_name }} minio/qgroundcontrol/builds/${{ github.ref_name }}/${{ inputs.artifact_name }} --region ap-northeast-2
      shell: bash

    - name: Upload tagged stable build to Minio latest Bucket
      if: github.event_name == 'push' && github.ref_type == 'tag'
      working-directory: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}
      run: |
        export MINIO_ACCESS_KEY=${{ inputs.minio_access_key }}
        export MINIO_SECRET_KEY=${{ inputs.minio_secret_key }}
        export MINIO_ENDPOINT=${{ inputs.minio_endpoint }}
        
        mc config host add minio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
        mc cp ${{ inputs.artifact_name }} minio/qgroundcontrol/latest/${{ inputs.artifact_name }}
      shell: bash
