name: pre-commit

# 비활성화됨
# on: [push, pull_request]
on: workflow_dispatch  # 수동 실행만 허용

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
